### ISSUE TITLE
error for configuring synapse enviornment

### ISSUE THREAD

**Issue by wenlong0213** [microsoft/SynapseVSCode#2]
below is the error detail:

Check if synapse spark kernel env has created... true
The synapse spark kernel env has been created, skip the creation process of conda env.
Download C:\ProgramData\anaconda3\envs\synapse-spark-kernel\lib\site-packages\delta.pth script completed, download to C:\ProgramData\anaconda3\envs\synapse-spark-kernel\lib\site-packages\delta.pth
Error: ENOENT: no such file or directory, open 'C:\ProgramData\anaconda3\envs\synapse-spark-kernel\lib\site-packages\delta.pth'
Installing PySpark releated packages error

**Comment by JoshLuedeman** [comment]
Having the same error

**Comment by qixwang** [comment]
thanks for the feedback.. we have identified the issue and will fix it soon. @ayzmkk-rongbi

**Comment by ayzmkk-rongbi** [comment]
Hi, @wenlong0213  and @JoshLuedeman 
Thanks for providing this issue. 

Please using the following steps to fix the error  "Error: ENOENT: no such file or directory, open 'C:\ProgramData\Anaconda3\envs\synapse-spark-kernel\lib\site-packages\delta.pt" 
**1) Remove env using** 
 conda remove -n synapse-spark-kernel --all 
**2) Update the extension version >= 0.2.9** 

Note: if it is the custom env location, **please run VS Code as administrator**
otherwise you may met this error:
CondaError: Unable to create prefix directory 'C:\Program Files\Anaconda3\envs\synapse-spark-kernel'.
Check that you have sufficient permissions.
